### ISSUE TITLE
Model Cleanup could have options for deleting Scope Boxes and Reference Planes

### ISSUE THREAD

**Issue by DuncanLithgow** [DuncanLithgow/EnTeeEeToolsIssues#5]
Model Cleanup could have options for deleting Scope Boxes and Reference Planes

**Comment by PeterTranberg** [comment]
What would be the usecase for deleting Scope Boxes. NTI TOOLS has a new function to keep linked Scope Boxes in Sync in Host Models, that gives value to the receiver of models so why delete them?. If we make this, I would suggest that all Scope Boxes should be individual selected and an option to select all. 
I understand the Usecase for Reference Planes. But here it is maybe just a delete all option that is needed?

**Comment by PeterTranberg** [comment]
Nej det er det ikke, troede du havde gjort det
